import { NextResponse } from "next/server";
import { checkIngestAuth } from "@/lib/auth-ingest";
import { syncBatchPostState } from "@/lib/batchState";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SERVICE_ROLE =
  (process.env.DM_INTERNAL_SUPABASE_SERVICE_ROLE_KEY ??
    process.env.SUPABASE_SERVICE_ROLE_KEY) ??
  "";

// Local rather than imported from @/lib/viral-slideshows — that module pulls in
// the Apify and ScrapeCreators scraper deps, which this read-only route has no
// use for.
function sbHeaders() {
  return {
    apikey: SERVICE_ROLE,
    Authorization: `Bearer ${SERVICE_ROLE}`,
    Accept: "application/json",
  };
}

interface BatchPost {
  batch_key: string;
  sort_order: number;
}

/**
 * Daily TikTok persona batches, written by claude/scripts/publish-batch-to-dash.py.
 * Read-only: the publisher writes straight to PostgREST with the service role,
 * so there's no POST here to defend.
 */
export async function GET(req: Request) {
  if (!checkIngestAuth(req)) {
    return NextResponse.json(
      { ok: false, error: "unauthorized" },
      { status: 401 },
    );
  }
  if (!SUPABASE_URL || !SERVICE_ROLE) {
    return NextResponse.json(
      { ok: false, error: "Supabase not configured" },
      { status: 500 },
    );
  }

  const limitRaw = Number(new URL(req.url).searchParams.get("limit"));
  const limit =
    Number.isFinite(limitRaw) && limitRaw > 0 ? Math.min(limitRaw, 200) : 30;

  try {
    // Refresh live post state first. Rate-limited and non-fatal inside: on
    // failure rows keep their last known state and render as unverified,
    // rather than the section asserting a stale "QUEUED".
    await syncBatchPostState();

    const batchRes = await fetch(
      `${SUPABASE_URL}/rest/v1/slideshow_batches` +
        `?select=*&order=batch_date.desc,batch_no.desc&limit=${limit}`,
      { headers: sbHeaders(), cache: "no-store" },
    );
    if (!batchRes.ok) {
      throw new Error(
        `slideshow_batches read failed: ${batchRes.status} ${await batchRes.text()}`,
      );
    }
    const batches = (await batchRes.json()) as Array<
      Record<string, unknown> & { batch_key: string }
    >;

    if (batches.length === 0) {
      return NextResponse.json({ ok: true, batches: [] });
    }

    // batch_key is generated by us ('virality28'), but quote each value anyway
    // so an unexpected character can't break out of the in.() list.
    const keys = batches
      .map((b) => `"${String(b.batch_key).replace(/"/g, "")}"`)
      .join(",");
    const postRes = await fetch(
      `${SUPABASE_URL}/rest/v1/slideshow_batch_posts` +
        `?select=*&batch_key=in.(${encodeURIComponent(keys)})&order=sort_order.asc`,
      { headers: sbHeaders(), cache: "no-store" },
    );
    if (!postRes.ok) {
      throw new Error(
        `slideshow_batch_posts read failed: ${postRes.status} ${await postRes.text()}`,
      );
    }
    const posts = (await postRes.json()) as BatchPost[];

    // Group server-side so the component never has to know about the join.
    const byBatch = new Map<string, BatchPost[]>();
    for (const p of posts) {
      const list = byBatch.get(p.batch_key);
      if (list) list.push(p);
      else byBatch.set(p.batch_key, [p]);
    }

    return NextResponse.json({
      ok: true,
      batches: batches.map((b) => ({
        ...b,
        posts: byBatch.get(b.batch_key) ?? [],
      })),
    });
  } catch (e) {
    return NextResponse.json(
      { ok: false, error: (e as Error).message },
      { status: 500 },
    );
  }
}
