import Link from "next/link";
import { FileText } from "lucide-react";
import { getLastRun, getRecentItemsByPersona } from "@/lib/queries";
import { PersonaColumn } from "@/components/PersonaColumn";
import { RunNowButton } from "@/components/RunNowButton";
import { formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function DailyContentPage() {
  const [{ personas, itemsByPersona }, lastRun] = await Promise.all([
    getRecentItemsByPersona(30),
    getLastRun(),
  ]);

  return (
    <div className="max-w-7xl mx-auto px-6 py-8">
      <header className="flex flex-wrap items-end justify-between gap-4 mb-6">
        <div>
          <div className="text-xs font-medium text-brand-600 mb-1">N8N</div>
          <h1 className="text-2xl font-semibold tracking-tight">
            Daily Content Pipeline
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Images + captions generated by the <em>DreamMe Daily Content Pipeline
            (3 Personas)</em> workflow.
          </p>
          {lastRun && (
            <p className="text-xs text-slate-500 mt-2">
              Last run: <span className="font-medium">{lastRun.status}</span> ·{" "}
              {formatDate(lastRun.finished_at ?? lastRun.started_at ?? "")}
              {lastRun.triggered_by ? ` · by ${lastRun.triggered_by}` : ""}
            </p>
          )}
        </div>
        <div className="flex items-center gap-3">
          <Link
            href="/dashboards/daily-content/captions"
            className="btn-outline"
          >
            <FileText className="size-4" />
            All captions
          </Link>
          <RunNowButton />
        </div>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {personas.map((p) => (
          <PersonaColumn
            key={p.id}
            persona={p}
            items={itemsByPersona[p.id] ?? []}
          />
        ))}
      </div>
    </div>
  );
}
